language: cpp

os:
  - linux
  - osx

 compiler:
    - gcc
    - clang
  
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      
    - os: osx
      osx_image: xcode7.2
      
    # gcc version 4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
      
    # gcc version 5.0
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
      
    # clang 3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
      
    # clang 3.7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install folly   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/fetch_folly_ubuntu_trusty.sh   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/prepare_ubuntu_trusty.sh   ; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j8
  - ./ReactiveSocketTest
