language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      compiler: clang
    - os: osx
      osx_image: xcode7.2


before_script:
  - ./scripts/fetch_folly_ubuntu_trusty.sh
  - ./scripts/prepare_ubuntu_trusty.sh
script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j8
  - ./ReactiveSocketTest
