sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

before_script:
  - ./scripts/fetch_folly_ubuntu_trusty.sh
  - ./scripts/prepare_ubuntu_trusty.sh
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=DEBUG
  - make -j8
  - ./tests
