sudo: required
dist: trusty

language: cpp

compiler:
  - gcc
  - clang

before_script:
  - ./scripts/fetch_folly_ubuntu_trusty.sh
  - ./scripts/prepare_ubuntu_trusty.sh
script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j8
  - ./ReactiveSocketTest
